# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:

  secret_key_base: 1c31bf1bedbaffd6be8b5044a1e55dbe635f55b6b73343587ceec9a749ac264a4f66802c0a965b72133a45a78573bbd9f84a598be985ec1f604b8d646b83b478

test:
  secret_key_base: 0c0e38fe9acf39beade42afec12f414532c0fbca0931d14c4e6be0b0c53aaca7c7a0eb8aa5177c0f2d40603f3cb45c6a759f1c2bbe250b5e3e36407b6611f65c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
